name: Bug Report
description: Create a report to help us fix a bug in DataSharedLib.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Thank you for reporting an issue!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the issue.
    validations:
      required: true
  - type: input
    id: dotnet-version
    attributes:
      label: .NET SDK Version
      placeholder: e.g., 10.0.100-preview.1
    validations:
      required: true
